version: '3.1'

services:
  db:
    container_name: product-service-db
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - .data:/var/lib/postgresql/data

volumes:
  pgdata: